### ISSUE TITLE
No dataloader/data_preprocessing/KITTI.kitti_utils in released code

### ISSUE THREAD

**Issue by xiaoliangbai** [ifnspaml/SGDepth#14]
Hello,

  Thanks for the open-source release. The download_kitti.py tries to import pcl_to_depth_map from dataloader.data_preprocessing.KITTI.kitti_utils, but there is no such directory/package in the master branch. Can you please also release the related code?

 Thanks,
Xiaoliang

**Comment by Ale0311** [comment]
Hello! 

I had the same problem when I first downloaded the repo. But then, on a closer look, I found on the README page a link to the dataloader repo as well. Here it is: 

https://github.com/ifnspaml/IFN_Dataloader

You have to download the necessary files/folders from there and put them in your project. 

Hope this helps.

**Comment by klingner** [comment]
Hello,

thank you for pointing out this bug and for supplying the fix already! I will update the repository accordingly.

**Comment by klingner** [comment]
I added the necessary files to the data_preprocessing folder. On my machine, the imports work fine now. Can you verify, if this also solves the problems for you?

**Comment by xiaoliangbai** [comment]
Thanks for the help, Ale0311 and Klingner! The downloading process is running. This issue has been resolved.
