### ISSUE TITLE
GPUs requirements and training time 

### ISSUE THREAD

**Issue by dongfengxijian** [ifnspaml/SGDepth#22]
Thank you for your great work! How many GPUs and how long I need to train SGDepth?

**Comment by klingner** [comment]
Hey, 
I usually train on one GPU (e.g., Tesla P100) and it takes approximately 40 hours. However, my bottleneck is still the data loading, so it might even be faster, depending on your hardware.

**Comment by dongfengxijian** [comment]
> Hey,
> I usually train on one GPU (e.g., Tesla P100) and it takes approximately 40 hours. However, my bottleneck is still the data loading, so it might even be faster, depending on your hardware.

Thank you for your replying！
