### ISSUE TITLE
Is the pretrained model correct?

### ISSUE THREAD

**Issue by Rodger-Huang** [ifnspaml/SGDepth#3]
Thank you for your great work.
When I used the pretrained model of _SGDepth full_ in _eval_segmentation.py_, I got the result like that
![image](https://user-images.githubusercontent.com/37412115/97322950-41f54780-18ab-11eb-914e-a676c0b92281.png)
However, when I used the pretrained model of _SGDepth only depth_ in _eval_segmentation.py_, I got the result like that
![image](https://user-images.githubusercontent.com/37412115/97323142-72d57c80-18ab-11eb-80a1-c3b60fb4a960.png)
So I want to know if the models have been swapped.

**Comment by klingner** [comment]
Hi, thanks for pointing this out. The download links were just mixed up. I fixed it in the README.
