### ISSUE TITLE
about eval and test 

### ISSUE THREAD

**Issue by xuchen-dev** [ifnspaml/SGDepth#31]
hi  i find validation during training  result  using kitti_kitti_validation  is better than test using kitti-zhou-test
![image](https://user-images.githubusercontent.com/79962968/155945268-dfa88433-e6b0-4b69-987d-c16292bcc43b.png)
![image](https://user-images.githubusercontent.com/79962968/155945462-91ccc5d2-6a11-4776-9bfc-5670cf4e86f4.png)

i wonder is kitti-zhou-test result is your paper provide  or kitti-kitti-validation  or other   like kitti-zhou-validation

**Comment by xuchen-dev** [comment]
kitti-zhou-validation  looks even better 
![image](https://user-images.githubusercontent.com/79962968/155971871-0b8da6a4-4c95-447b-9253-0257b43920c4.png)

**Comment by klingner** [comment]
I am not quite sure what you are aiming at. Results on different datasets are of course different and not comparable. A better result on one dataset mainly tells you that the dataset is easier for the model. In the paper mainly results on kitti_zhou_test are reported as is common.

**Comment by xuchen-dev** [comment]
thank you
